# Use uma imagem base
FROM ubuntu:20.04

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY . .

# Especifique o comando de inicialização
CMD ["bash"]
