name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
        
      - uses: actions/checkout@v4.0.0
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: matheus183
          password: ${{ secrets.PASSWD}}
            
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          file: .
          push: true
          tags: |
            matheuscardosoKono/matheuscardoso:v1
            matheuscardosoKono/matheuscardoso:latest
        

          
